package com.segnities007.canimation.screen.examples

import kotlin.jvm.JvmInline

/**
 * Typed demo variants used by gallery/detail screens.
 */
enum class DemoType {
    Effect,
    Transition,
    Composition,
    Stagger,
    Emphasis,
    RealWorld,
    Component,
    EnterExit,
    Visibility,
}

/**
 * Typed key for component demo registry lookups.
 */
@JvmInline
value class ComponentDemoKey(val value: String)

/**
 * SSoT for all component demo IDs.
 */
object ComponentDemoKeys {
    val AnimatedAccordion = ComponentDemoKey("AnimatedAccordion")
    val AnimatedAlert = ComponentDemoKey("AnimatedAlert")
    val AnimatedBanner = ComponentDemoKey("AnimatedBanner")
    val AnimatedBarChart = ComponentDemoKey("AnimatedBarChart")
    val AnimatedBottomSheet = ComponentDemoKey("AnimatedBottomSheet")
    val AnimatedBreadcrumb = ComponentDemoKey("AnimatedBreadcrumb")
    val AnimatedCheckmark = ComponentDemoKey("AnimatedCheckmark")
    val AnimatedChipGroup = ComponentDemoKey("AnimatedChipGroup")
    val AnimatedChipInput = ComponentDemoKey("AnimatedChipInput")
    val AnimatedCodeBlock = ComponentDemoKey("AnimatedCodeBlock")
    val AnimatedColorPicker = ComponentDemoKey("AnimatedColorPicker")
    val AnimatedCountdownTimer = ComponentDemoKey("AnimatedCountdownTimer")
    val AnimatedCounter = ComponentDemoKey("AnimatedCounter")
    val AnimatedCreditCard = ComponentDemoKey("AnimatedCreditCard")
    val AnimatedDialog = ComponentDemoKey("AnimatedDialog")
    val AnimatedDropdown = ComponentDemoKey("AnimatedDropdown")
    val AnimatedFab = ComponentDemoKey("AnimatedFab")
    val AnimatedFeatureGrid = ComponentDemoKey("AnimatedFeatureGrid")
    val AnimatedFileUpload = ComponentDemoKey("AnimatedFileUpload")
    val AnimatedFormValidation = ComponentDemoKey("AnimatedFormValidation")
    val AnimatedGradientText = ComponentDemoKey("AnimatedGradientText")
    val AnimatedKpi = ComponentDemoKey("AnimatedKpi")
    val AnimatedListItem = ComponentDemoKey("AnimatedListItem")
    val AnimatedNavItem = ComponentDemoKey("AnimatedNavItem")
    val AnimatedNotificationBell = ComponentDemoKey("AnimatedNotificationBell")
    val AnimatedPasswordField = ComponentDemoKey("AnimatedPasswordField")
    val AnimatedPieChart = ComponentDemoKey("AnimatedPieChart")
    val AnimatedPinInput = ComponentDemoKey("AnimatedPinInput")
    val AnimatedPricingToggle = ComponentDemoKey("AnimatedPricingToggle")
    val AnimatedProgressCard = ComponentDemoKey("AnimatedProgressCard")
    val AnimatedRating = ComponentDemoKey("AnimatedRating")
    val AnimatedSearchBar = ComponentDemoKey("AnimatedSearchBar")
    val AnimatedSearchResult = ComponentDemoKey("AnimatedSearchResult")
    val AnimatedSnackbar = ComponentDemoKey("AnimatedSnackbar")
    val AnimatedStatCard = ComponentDemoKey("AnimatedStatCard")
    val AnimatedStepper = ComponentDemoKey("AnimatedStepper")
    val AnimatedSwitch = ComponentDemoKey("AnimatedSwitch")
    val AnimatedTabs = ComponentDemoKey("AnimatedTabs")
    val AnimatedTagCloud = ComponentDemoKey("AnimatedTagCloud")
    val AnimatedThemeToggle = ComponentDemoKey("AnimatedThemeToggle")
    val AnimatedTimeline = ComponentDemoKey("AnimatedTimeline")
    val AnimatedTooltip = ComponentDemoKey("AnimatedTooltip")
    val AnimatedUnderlineText = ComponentDemoKey("AnimatedUnderlineText")
    val AnimatedVote = ComponentDemoKey("AnimatedVote")
    val BottomNavBar = ComponentDemoKey("BottomNavBar")
    val BouncingBall = ComponentDemoKey("BouncingBall")
    val BouncingLoader = ComponentDemoKey("BouncingLoader")
    val BouncySpringList = ComponentDemoKey("BouncySpringList")
    val CardBorderTrace = ComponentDemoKey("CardBorderTrace")
    val CardExpandCollapse = ComponentDemoKey("CardExpandCollapse")
    val CardFanStack = ComponentDemoKey("CardFanStack")
    val CardGlassmorphism = ComponentDemoKey("CardGlassmorphism")
    val CardGradientBorder = ComponentDemoKey("CardGradientBorder")
    val CardLiftHover = ComponentDemoKey("CardLiftHover")
    val CardMagneticSnap = ComponentDemoKey("CardMagneticSnap")
    val CardParallaxTilt = ComponentDemoKey("CardParallaxTilt")
    val CardRevealWipe = ComponentDemoKey("CardRevealWipe")
    val CardShuffle = ComponentDemoKey("CardShuffle")
    val CardStackSwipe = ComponentDemoKey("CardStackSwipe")
    val CheckboxAnimation = ComponentDemoKey("CheckboxAnimation")
    val CircularMenu = ComponentDemoKey("CircularMenu")
    val CircularRevealCard = ComponentDemoKey("CircularRevealCard")
    val CoinFlip = ComponentDemoKey("CoinFlip")
    val ColorMorph = ComponentDemoKey("ColorMorph")
    val ColorSwatchPicker = ComponentDemoKey("ColorSwatchPicker")
    val CommandPalette = ComponentDemoKey("CommandPalette")
    val ConfettiExplosion = ComponentDemoKey("ConfettiExplosion")
    val DataTable = ComponentDemoKey("DataTable")
    val DnaHelixCanvas = ComponentDemoKey("DnaHelixCanvas")
    val DonutChart = ComponentDemoKey("DonutChart")
    val ElasticDrawer = ComponentDemoKey("ElasticDrawer")
    val ElasticPull = ComponentDemoKey("ElasticPull")
    val EngagementStats = ComponentDemoKey("EngagementStats")
    val EventCard = ComponentDemoKey("EventCard")
    val ExpandableChip = ComponentDemoKey("ExpandableChip")
    val ExpandingSearch = ComponentDemoKey("ExpandingSearch")
    val FlipCard = ComponentDemoKey("FlipCard")
    val FlipCounter = ComponentDemoKey("FlipCounter")
    val FloatingParticles = ComponentDemoKey("FloatingParticles")
    val FocusBlurEffect = ComponentDemoKey("FocusBlurEffect")
    val GaugeChart = ComponentDemoKey("GaugeChart")
    val GlitchText = ComponentDemoKey("GlitchText")
    val GlowProgressBar = ComponentDemoKey("GlowProgressBar")
    val GlowPulse = ComponentDemoKey("GlowPulse")
    val GradientBorderCard = ComponentDemoKey("GradientBorderCard")
    val GradientShift = ComponentDemoKey("GradientShift")
    val HeartbeatLine = ComponentDemoKey("HeartbeatLine")
    val HexGrid = ComponentDemoKey("HexGrid")
    val HoldToConfirm = ComponentDemoKey("HoldToConfirm")
    val HorizontalBarChart = ComponentDemoKey("HorizontalBarChart")
    val HorizontalScrollGallery = ComponentDemoKey("HorizontalScrollGallery")
    val IOSSlider = ComponentDemoKey("IOSSlider")
    val InfiniteLoadingList = ComponentDemoKey("InfiniteLoadingList")
    val LikeButton = ComponentDemoKey("LikeButton")
    val LiquidFill = ComponentDemoKey("LiquidFill")
    val LiveCounter = ComponentDemoKey("LiveCounter")
    val MagneticButton = ComponentDemoKey("MagneticButton")
    val MatrixRain = ComponentDemoKey("MatrixRain")
    val MegaMenuReveal = ComponentDemoKey("MegaMenuReveal")
    val MetricCard = ComponentDemoKey("MetricCard")
    val MiniBarChart = ComponentDemoKey("MiniBarChart")
    val MorphProgressIndicator = ComponentDemoKey("MorphProgressIndicator")
    val MorphingShape = ComponentDemoKey("MorphingShape")
    val MultiStateBadge = ComponentDemoKey("MultiStateBadge")
    val MusicEqualizer = ComponentDemoKey("MusicEqualizer")
    val MusicPlayerCard = ComponentDemoKey("MusicPlayerCard")
    val NeumorphismCard = ComponentDemoKey("NeumorphismCard")
    val NotificationCard = ComponentDemoKey("NotificationCard")
    val OrbitDots = ComponentDemoKey("OrbitDots")
    val PaginationDots = ComponentDemoKey("PaginationDots")
    val ParallaxLayers = ComponentDemoKey("ParallaxLayers")
    val ParticleField = ComponentDemoKey("ParticleField")
    val PathTracer = ComponentDemoKey("PathTracer")
    val PendulumSwing = ComponentDemoKey("PendulumSwing")
    val PriceSwitcher = ComponentDemoKey("PriceSwitcher")
    val PricingCard = ComponentDemoKey("PricingCard")
    val ProductCard = ComponentDemoKey("ProductCard")
    val ProfileCard = ComponentDemoKey("ProfileCard")
    val ProgressRing = ComponentDemoKey("ProgressRing")
    val ProgressScrubber = ComponentDemoKey("ProgressScrubber")
    val PulseButton = ComponentDemoKey("PulseButton")
    val PulseLoadingDots = ComponentDemoKey("PulseLoadingDots")
    val PulseRadar = ComponentDemoKey("PulseRadar")
    val PulseRing = ComponentDemoKey("PulseRing")
    val PulsingAvatar = ComponentDemoKey("PulsingAvatar")
    val QuantitySelector = ComponentDemoKey("QuantitySelector")
    val RadarChart = ComponentDemoKey("RadarChart")
    val RadialProgress = ComponentDemoKey("RadialProgress")
    val RadioSelector = ComponentDemoKey("RadioSelector")
    val RecipeCard = ComponentDemoKey("RecipeCard")
    val RevealTextEffect = ComponentDemoKey("RevealTextEffect")
    val RippleButton = ComponentDemoKey("RippleButton")
    val RollingDigits = ComponentDemoKey("RollingDigits")
    val RotatingCube = ComponentDemoKey("RotatingCube")
    val RotatingSquares = ComponentDemoKey("RotatingSquares")
    val ScatterText = ComponentDemoKey("ScatterText")
    val ScrambleText = ComponentDemoKey("ScrambleText")
    val ScrollDirectionHeader = ComponentDemoKey("ScrollDirectionHeader")
    val SegmentedControl = ComponentDemoKey("SegmentedControl")
    val ShimmerEffect = ComponentDemoKey("ShimmerEffect")
    val SideMenuReveal = ComponentDemoKey("SideMenuReveal")
    val SkeletonLoader = ComponentDemoKey("SkeletonLoader")
    val SliderControl = ComponentDemoKey("SliderControl")
    val SlidingReveal = ComponentDemoKey("SlidingReveal")
    val SlinkySpring = ComponentDemoKey("SlinkySpring")
    val SlotMachine = ComponentDemoKey("SlotMachine")
    val SmoothTabIndicator = ComponentDemoKey("SmoothTabIndicator")
    val SparkLine = ComponentDemoKey("SparkLine")
    val SpiralDots = ComponentDemoKey("SpiralDots")
    val SplitTextReveal = ComponentDemoKey("SplitTextReveal")
    val SpringChain = ComponentDemoKey("SpringChain")
    val SpringChip = ComponentDemoKey("SpringChip")
    val StackedAvatars = ComponentDemoKey("StackedAvatars")
    val StackedNotifications = ComponentDemoKey("StackedNotifications")
    val StaggerFromCenter = ComponentDemoKey("StaggerFromCenter")
    val SwipeActions = ComponentDemoKey("SwipeActions")
    val SwipeCard = ComponentDemoKey("SwipeCard")
    val SwitchAnimation = ComponentDemoKey("SwitchAnimation")
    val TestimonialCard = ComponentDemoKey("TestimonialCard")
    val TextFadeReveal = ComponentDemoKey("TextFadeReveal")
    val TextGlitch = ComponentDemoKey("TextGlitch")
    val TextGradientReveal = ComponentDemoKey("TextGradientReveal")
    val TextHighlighter = ComponentDemoKey("TextHighlighter")
    val TextLineReveal = ComponentDemoKey("TextLineReveal")
    val TextMorph = ComponentDemoKey("TextMorph")
    val TextRotateWords = ComponentDemoKey("TextRotateWords")
    val TextShuffleWord = ComponentDemoKey("TextShuffleWord")
    val TextStrikethrough = ComponentDemoKey("TextStrikethrough")
    val TickerMarquee = ComponentDemoKey("TickerMarquee")
    val TiltCard = ComponentDemoKey("TiltCard")
    val ToastNotification = ComponentDemoKey("ToastNotification")
    val TypewriterDelete = ComponentDemoKey("TypewriterDelete")
    val TypewriterEffect = ComponentDemoKey("TypewriterEffect")
    val VerticalCarousel = ComponentDemoKey("VerticalCarousel")
    val VerticalTicker = ComponentDemoKey("VerticalTicker")
    val WaterDroplet = ComponentDemoKey("WaterDroplet")
    val WaterfallGrid = ComponentDemoKey("WaterfallGrid")
    val WaveEffect = ComponentDemoKey("WaveEffect")
    val WaveProgressBar = ComponentDemoKey("WaveProgressBar")
    val WaveformBars = ComponentDemoKey("WaveformBars")
    val WaveformVisualizer = ComponentDemoKey("WaveformVisualizer")
    val WavyText = ComponentDemoKey("WavyText")
    val WeatherCard = ComponentDemoKey("WeatherCard")
    val ZoomHeroImage = ComponentDemoKey("ZoomHeroImage")
}
