package com.segnities007.canimation.screen.examples

import io.github.canimation.core.Canimation
import io.github.canimation.core.CanimationEffect
import io.github.canimation.core.CanimationPreset
import canimation.composeapp.generated.resources.*



internal val exampleCategoriesChunk02Part03: List<ExampleCategory> = listOf(
        // 22. Real World Patterns
        ExampleCategory(
            id = "real-world",
            title = Res.string.examples_data_real_world_title,
            subtitle = Res.string.examples_data_real_world_subtitle,
            accentLabel = "UI",
            tags = listOf("UI", "PATTERN"),
            examples = listOf(
                ExampleItem(
                    title = Res.string.examples_data_real_world_item_01_title,
                    description = Res.string.examples_data_real_world_item_01_description,
                    demoType = DemoType.RealWorld,
                    effect = Canimation.Fade.Up + Canimation.Scale.Subtle,
                    preset = CanimationPreset.FadeUp,
                    codeSnippet = Res.string.examples_data_real_world_item_01_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_real_world_item_02_title,
                    description = Res.string.examples_data_real_world_item_02_description,
                    demoType = DemoType.RealWorld,
                    effect = Canimation.Slide.Right + Canimation.Fade.In,
                    preset = CanimationPreset.SlideRight,
                    codeSnippet = Res.string.examples_data_real_world_item_02_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_real_world_item_03_title,
                    description = Res.string.examples_data_real_world_item_03_description,
                    demoType = DemoType.RealWorld,
                    effect = Canimation.Entrance.Drop,
                    preset = CanimationPreset.DropIn,
                    codeSnippet = Res.string.examples_data_real_world_item_03_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_real_world_item_04_title,
                    description = Res.string.examples_data_real_world_item_04_description,
                    demoType = DemoType.Emphasis,
                    preset = CanimationPreset.Pulse,
                    codeSnippet = Res.string.examples_data_real_world_item_04_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_real_world_item_05_title,
                    description = Res.string.examples_data_real_world_item_05_description,
                    demoType = DemoType.RealWorld,
                    effect = Canimation.Scale.Pop + Canimation.Fade.In,
                    preset = CanimationPreset.Pop,
                    codeSnippet = Res.string.examples_data_real_world_item_05_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_real_world_item_06_title,
                    description = Res.string.examples_data_real_world_item_06_description,
                    demoType = DemoType.Transition,
                    enterEffect = Canimation.Material.FadeThrough,
                    exitEffect = Canimation.Material.FadeThrough,
                    preset = CanimationPreset.FadeThrough,
                    codeSnippet = Res.string.examples_data_real_world_item_06_code,
                ),
            ),
        ),
        // ── Text & Typography ──
        ExampleCategory(
            id = "text-typography",
            title = Res.string.examples_data_text_typography_title,
            subtitle = Res.string.examples_data_text_typography_subtitle,
            accentLabel = "TEXT",
            tags = listOf("TEXT"),
            examples = listOf(
                ExampleItem(
                    title = Res.string.examples_data_text_typography_item_01_title,
                    description = Res.string.examples_data_text_typography_item_01_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.ScrambleText,
                    codeSnippet = Res.string.examples_data_text_typography_item_07_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_text_typography_item_02_title,
                    description = Res.string.examples_data_text_typography_item_02_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.WavyText,
                    codeSnippet = Res.string.examples_data_text_typography_item_08_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_text_typography_item_03_title,
                    description = Res.string.examples_data_text_typography_item_03_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.SplitTextReveal,
                    codeSnippet = Res.string.examples_data_text_typography_item_09_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_text_typography_item_04_title,
                    description = Res.string.examples_data_text_typography_item_04_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.GlitchText,
                    codeSnippet = Res.string.examples_data_text_typography_item_10_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_text_typography_item_05_title,
                    description = Res.string.examples_data_text_typography_item_05_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.RollingDigits,
                    codeSnippet = Res.string.examples_data_text_typography_item_11_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_text_typography_item_06_title,
                    description = Res.string.examples_data_text_typography_item_06_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.VerticalTicker,
                    codeSnippet = Res.string.examples_data_text_typography_item_12_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_text_typography_item_07_title,
                    description = Res.string.examples_data_text_typography_item_07_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.AnimatedUnderlineText,
                    codeSnippet = Res.string.examples_data_text_typography_item_13_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_text_typography_item_08_title,
                    description = Res.string.examples_data_text_typography_item_08_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.AnimatedGradientText,
                    codeSnippet = Res.string.examples_data_text_typography_item_14_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_text_typography_item_09_title,
                    description = Res.string.examples_data_text_typography_item_09_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.RevealTextEffect,
                    codeSnippet = Res.string.examples_data_text_typography_item_15_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_text_typography_item_10_title,
                    description = Res.string.examples_data_text_typography_item_10_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.ScatterText,
                    codeSnippet = Res.string.examples_data_text_typography_item_16_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_text_typography_item_11_title,
                    description = Res.string.examples_data_text_typography_item_11_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.TextLineReveal,
                    codeSnippet = Res.string.examples_data_text_typography_item_17_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_text_typography_item_12_title,
                    description = Res.string.examples_data_text_typography_item_12_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.TypewriterDelete,
                    codeSnippet = Res.string.examples_data_text_typography_item_18_code,
                ),
            ),
        ),
        // ── Cards & Surfaces ──
        ExampleCategory(
            id = "cards-surfaces",
            title = Res.string.examples_data_cards_surfaces_title,
            subtitle = Res.string.examples_data_cards_surfaces_subtitle,
            accentLabel = "CARDS",
            tags = listOf("CARDS"),
            examples = listOf(
                ExampleItem(
                    title = Res.string.examples_data_cards_surfaces_item_01_title,
                    description = Res.string.examples_data_cards_surfaces_item_01_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.FlipCard,
                    codeSnippet = Res.string.examples_data_cards_surfaces_item_19_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_cards_surfaces_item_02_title,
                    description = Res.string.examples_data_cards_surfaces_item_02_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.TiltCard,
                    codeSnippet = Res.string.examples_data_cards_surfaces_item_20_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_cards_surfaces_item_03_title,
                    description = Res.string.examples_data_cards_surfaces_item_03_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.CardBorderTrace,
                    codeSnippet = Res.string.examples_data_cards_surfaces_item_21_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_cards_surfaces_item_04_title,
                    description = Res.string.examples_data_cards_surfaces_item_04_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.CardLiftHover,
                    codeSnippet = Res.string.examples_data_cards_surfaces_item_22_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_cards_surfaces_item_05_title,
                    description = Res.string.examples_data_cards_surfaces_item_05_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.CardGradientBorder,
                    codeSnippet = Res.string.examples_data_cards_surfaces_item_23_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_cards_surfaces_item_06_title,
                    description = Res.string.examples_data_cards_surfaces_item_06_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.CardExpandCollapse,
                    codeSnippet = Res.string.examples_data_cards_surfaces_item_24_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_cards_surfaces_item_07_title,
                    description = Res.string.examples_data_cards_surfaces_item_07_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.CardParallaxTilt,
                    codeSnippet = Res.string.examples_data_cards_surfaces_item_25_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_cards_surfaces_item_08_title,
                    description = Res.string.examples_data_cards_surfaces_item_08_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.CardGlassmorphism,
                    codeSnippet = Res.string.examples_data_cards_surfaces_item_26_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_cards_surfaces_item_09_title,
                    description = Res.string.examples_data_cards_surfaces_item_09_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.CardRevealWipe,
                    codeSnippet = Res.string.examples_data_cards_surfaces_item_27_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_cards_surfaces_item_10_title,
                    description = Res.string.examples_data_cards_surfaces_item_10_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.CardFanStack,
                    codeSnippet = Res.string.examples_data_cards_surfaces_item_28_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_cards_surfaces_item_11_title,
                    description = Res.string.examples_data_cards_surfaces_item_11_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.CardMagneticSnap,
                    codeSnippet = Res.string.examples_data_cards_surfaces_item_29_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_cards_surfaces_item_12_title,
                    description = Res.string.examples_data_cards_surfaces_item_12_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.CardShuffle,
                    codeSnippet = Res.string.examples_data_cards_surfaces_item_30_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_cards_surfaces_item_13_title,
                    description = Res.string.examples_data_cards_surfaces_item_13_description,
                    demoType = DemoType.Component,
                    componentKey = ComponentDemoKeys.CardStackSwipe,
                    codeSnippet = Res.string.examples_data_cards_surfaces_item_31_code,
                ),
            ),
        ),
)
