package com.segnities007.canimation.screen.examples

import io.github.canimation.core.Canimation
import io.github.canimation.core.CanimationEffect
import io.github.canimation.core.CanimationPreset
import canimation.composeapp.generated.resources.*



internal val exampleCategoriesChunk02Part01: List<ExampleCategory> = listOf(
        // 13. Zoom Effects
        ExampleCategory(
            id = "zoom",
            title = Res.string.examples_data_zoom_title,
            subtitle = Res.string.examples_data_zoom_subtitle,
            accentLabel = "ENTRANCE",
            tags = listOf("ENTRANCE"),
            examples = listOf(
                ExampleItem(
                    title = Res.string.examples_data_zoom_item_01_title,
                    description = Res.string.examples_data_zoom_item_01_description,
                    effect = Canimation.Zoom.In,
                    preset = CanimationPreset.ZoomIn,
                    codeSnippet = Res.string.examples_data_zoom_item_01_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_zoom_item_02_title,
                    description = Res.string.examples_data_zoom_item_02_description,
                    effect = Canimation.Zoom.Out,
                    preset = CanimationPreset.ZoomOut,
                    codeSnippet = Res.string.examples_data_zoom_item_02_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_zoom_item_03_title,
                    description = Res.string.examples_data_zoom_item_03_description,
                    effect = Canimation.Zoom.InUp,
                    preset = CanimationPreset.ZoomInUp,
                    codeSnippet = Res.string.examples_data_zoom_item_03_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_zoom_item_04_title,
                    description = Res.string.examples_data_zoom_item_04_description,
                    effect = Canimation.Zoom.InDown,
                    preset = CanimationPreset.ZoomInDown,
                    codeSnippet = Res.string.examples_data_zoom_item_04_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_zoom_item_05_title,
                    description = Res.string.examples_data_zoom_item_05_description,
                    effect = Canimation.Zoom.InLeft,
                    preset = CanimationPreset.ZoomInLeft,
                    codeSnippet = Res.string.examples_data_zoom_item_05_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_zoom_item_06_title,
                    description = Res.string.examples_data_zoom_item_06_description,
                    effect = Canimation.Zoom.InRight,
                    preset = CanimationPreset.ZoomInRight,
                    codeSnippet = Res.string.examples_data_zoom_item_06_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_zoom_item_07_title,
                    description = Res.string.examples_data_zoom_item_07_description,
                    effect = Canimation.Zoom.Dramatic,
                    preset = CanimationPreset.ZoomIn,
                    codeSnippet = Res.string.examples_data_zoom_item_07_code,
                ),
            ),
        ),
        // 14. Attention Seekers
        ExampleCategory(
            id = "attention",
            title = Res.string.examples_data_attention_title,
            subtitle = Res.string.examples_data_attention_subtitle,
            accentLabel = "EMPHASIS",
            tags = listOf("EMPHASIS"),
            examples = listOf(
                ExampleItem(
                    title = Res.string.examples_data_attention_item_01_title,
                    description = Res.string.examples_data_attention_item_01_description,
                    demoType = DemoType.Emphasis,
                    preset = CanimationPreset.Pulse,
                    codeSnippet = Res.string.examples_data_attention_item_08_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_attention_item_02_title,
                    description = Res.string.examples_data_attention_item_02_description,
                    demoType = DemoType.Emphasis,
                    preset = CanimationPreset.HeartBeat,
                    codeSnippet = Res.string.examples_data_attention_item_09_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_attention_item_03_title,
                    description = Res.string.examples_data_attention_item_03_description,
                    demoType = DemoType.Emphasis,
                    preset = CanimationPreset.Tada,
                    codeSnippet = Res.string.examples_data_attention_item_10_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_attention_item_04_title,
                    description = Res.string.examples_data_attention_item_04_description,
                    demoType = DemoType.Emphasis,
                    preset = CanimationPreset.Wobble,
                    codeSnippet = Res.string.examples_data_attention_item_11_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_attention_item_05_title,
                    description = Res.string.examples_data_attention_item_05_description,
                    demoType = DemoType.Emphasis,
                    preset = CanimationPreset.Swing,
                    codeSnippet = Res.string.examples_data_attention_item_12_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_attention_item_06_title,
                    description = Res.string.examples_data_attention_item_06_description,
                    demoType = DemoType.Emphasis,
                    preset = CanimationPreset.RubberBand,
                    codeSnippet = Res.string.examples_data_attention_item_13_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_attention_item_07_title,
                    description = Res.string.examples_data_attention_item_07_description,
                    demoType = DemoType.Emphasis,
                    preset = CanimationPreset.Jello,
                    codeSnippet = Res.string.examples_data_attention_item_14_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_attention_item_08_title,
                    description = Res.string.examples_data_attention_item_08_description,
                    demoType = DemoType.Emphasis,
                    preset = CanimationPreset.Flash,
                    codeSnippet = Res.string.examples_data_attention_item_15_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_attention_item_09_title,
                    description = Res.string.examples_data_attention_item_09_description,
                    demoType = DemoType.Emphasis,
                    preset = CanimationPreset.ShakeX,
                    codeSnippet = Res.string.examples_data_attention_item_16_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_attention_item_10_title,
                    description = Res.string.examples_data_attention_item_10_description,
                    demoType = DemoType.Emphasis,
                    preset = CanimationPreset.ShakeY,
                    codeSnippet = Res.string.examples_data_attention_item_17_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_attention_item_11_title,
                    description = Res.string.examples_data_attention_item_11_description,
                    demoType = DemoType.Emphasis,
                    preset = CanimationPreset.HeadShake,
                    codeSnippet = Res.string.examples_data_attention_item_18_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_attention_item_12_title,
                    description = Res.string.examples_data_attention_item_12_description,
                    demoType = DemoType.Emphasis,
                    preset = CanimationPreset.Bounce,
                    codeSnippet = Res.string.examples_data_attention_item_19_code,
                ),
            ),
        ),
        // 15. Dramatic Entrances
        ExampleCategory(
            id = "entrance",
            title = Res.string.examples_data_entrance_title,
            subtitle = Res.string.examples_data_entrance_subtitle,
            accentLabel = "ENTRANCE",
            tags = listOf("ENTRANCE"),
            examples = listOf(
                ExampleItem(
                    title = Res.string.examples_data_entrance_item_01_title,
                    description = Res.string.examples_data_entrance_item_01_description,
                    effect = Canimation.Entrance.Elevate,
                    preset = CanimationPreset.ElevateIn,
                    codeSnippet = Res.string.examples_data_entrance_item_20_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_entrance_item_02_title,
                    description = Res.string.examples_data_entrance_item_02_description,
                    effect = Canimation.Entrance.Drop,
                    preset = CanimationPreset.DropIn,
                    codeSnippet = Res.string.examples_data_entrance_item_21_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_entrance_item_03_title,
                    description = Res.string.examples_data_entrance_item_03_description,
                    effect = Canimation.Entrance.JackInTheBox,
                    preset = CanimationPreset.JackInTheBox,
                    codeSnippet = Res.string.examples_data_entrance_item_22_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_entrance_item_04_title,
                    description = Res.string.examples_data_entrance_item_04_description,
                    effect = Canimation.Entrance.RollIn,
                    preset = CanimationPreset.RollIn,
                    codeSnippet = Res.string.examples_data_entrance_item_23_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_entrance_item_05_title,
                    description = Res.string.examples_data_entrance_item_05_description,
                    effect = Canimation.Entrance.LightSpeedLeft,
                    preset = CanimationPreset.LightSpeedInLeft,
                    codeSnippet = Res.string.examples_data_entrance_item_24_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_entrance_item_06_title,
                    description = Res.string.examples_data_entrance_item_06_description,
                    effect = Canimation.Entrance.LightSpeedRight,
                    preset = CanimationPreset.LightSpeedInRight,
                    codeSnippet = Res.string.examples_data_entrance_item_25_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_entrance_item_07_title,
                    description = Res.string.examples_data_entrance_item_07_description,
                    effect = Canimation.Entrance.Snap,
                    preset = CanimationPreset.Snap,
                    codeSnippet = Res.string.examples_data_entrance_item_26_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_entrance_item_08_title,
                    description = Res.string.examples_data_entrance_item_08_description,
                    effect = Canimation.Entrance.SwingIn,
                    preset = CanimationPreset.SwingIn,
                    codeSnippet = Res.string.examples_data_entrance_item_27_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_entrance_item_09_title,
                    description = Res.string.examples_data_entrance_item_09_description,
                    effect = Canimation.Entrance.Unfold,
                    preset = CanimationPreset.ElevateIn,
                    codeSnippet = Res.string.examples_data_entrance_item_28_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_entrance_item_10_title,
                    description = Res.string.examples_data_entrance_item_10_description,
                    effect = Canimation.Entrance.Rise,
                    preset = CanimationPreset.FadeUp,
                    codeSnippet = Res.string.examples_data_entrance_item_29_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_entrance_item_11_title,
                    description = Res.string.examples_data_entrance_item_11_description,
                    effect = Canimation.Entrance.Emerge,
                    preset = CanimationPreset.ScaleIn,
                    codeSnippet = Res.string.examples_data_entrance_item_30_code,
                ),
            ),
        ),
        // 16. Back Entrances
        ExampleCategory(
            id = "entrance-back",
            title = Res.string.examples_data_entrance_back_title,
            subtitle = Res.string.examples_data_entrance_back_subtitle,
            accentLabel = "ENTRANCE",
            tags = listOf("ENTRANCE", "DIRECTION"),
            examples = listOf(
                ExampleItem(
                    title = Res.string.examples_data_entrance_back_item_01_title,
                    description = Res.string.examples_data_entrance_back_item_01_description,
                    effect = Canimation.Entrance.BackInUp,
                    preset = CanimationPreset.BackInUp,
                    codeSnippet = Res.string.examples_data_entrance_back_item_31_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_entrance_back_item_02_title,
                    description = Res.string.examples_data_entrance_back_item_02_description,
                    effect = Canimation.Entrance.BackInDown,
                    preset = CanimationPreset.BackInDown,
                    codeSnippet = Res.string.examples_data_entrance_back_item_32_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_entrance_back_item_03_title,
                    description = Res.string.examples_data_entrance_back_item_03_description,
                    effect = Canimation.Entrance.BackInLeft,
                    preset = CanimationPreset.BackInLeft,
                    codeSnippet = Res.string.examples_data_entrance_back_item_33_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_entrance_back_item_04_title,
                    description = Res.string.examples_data_entrance_back_item_04_description,
                    effect = Canimation.Entrance.BackInRight,
                    preset = CanimationPreset.BackInRight,
                    codeSnippet = Res.string.examples_data_entrance_back_item_34_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_entrance_back_item_05_title,
                    description = Res.string.examples_data_entrance_back_item_05_description,
                    effect = Canimation.Entrance.ShrinkIn,
                    preset = CanimationPreset.ShrinkIn,
                    codeSnippet = Res.string.examples_data_entrance_back_item_35_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_entrance_back_item_06_title,
                    description = Res.string.examples_data_entrance_back_item_06_description,
                    effect = Canimation.Entrance.TiltIn,
                    preset = CanimationPreset.TiltIn,
                    codeSnippet = Res.string.examples_data_entrance_back_item_36_code,
                ),
            ),
        ),
        // 17. Material Motion
        ExampleCategory(
            id = "material",
            title = Res.string.examples_data_material_title,
            subtitle = Res.string.examples_data_material_subtitle,
            accentLabel = "MATERIAL",
            tags = listOf("MATERIAL"),
            examples = listOf(
                ExampleItem(
                    title = Res.string.examples_data_material_item_01_title,
                    description = Res.string.examples_data_material_item_01_description,
                    effect = Canimation.Material.FadeThrough,
                    preset = CanimationPreset.FadeThrough,
                    codeSnippet = Res.string.examples_data_material_item_37_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_material_item_02_title,
                    description = Res.string.examples_data_material_item_02_description,
                    effect = Canimation.Material.SharedAxisX,
                    preset = CanimationPreset.SharedAxisX,
                    codeSnippet = Res.string.examples_data_material_item_38_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_material_item_03_title,
                    description = Res.string.examples_data_material_item_03_description,
                    effect = Canimation.Material.SharedAxisY,
                    preset = CanimationPreset.SharedAxisY,
                    codeSnippet = Res.string.examples_data_material_item_39_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_material_item_04_title,
                    description = Res.string.examples_data_material_item_04_description,
                    effect = Canimation.Material.SharedAxisZ,
                    preset = CanimationPreset.SharedAxisX,
                    codeSnippet = Res.string.examples_data_material_item_40_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_material_item_05_title,
                    description = Res.string.examples_data_material_item_05_description,
                    effect = Canimation.Material.Emphasized,
                    preset = CanimationPreset.EmphasizedEntry,
                    codeSnippet = Res.string.examples_data_material_item_41_code,
                ),
                ExampleItem(
                    title = Res.string.examples_data_material_item_06_title,
                    description = Res.string.examples_data_material_item_06_description,
                    effect = Canimation.Material.ContainerTransform,
                    preset = CanimationPreset.EmphasizedEntry,
                    codeSnippet = Res.string.examples_data_material_item_42_code,
                ),
            ),
        ),
)
