package com.segnities007.canimation.screen.examples

import io.github.canimation.core.Canimation
import io.github.canimation.core.CanimationEffect
import io.github.canimation.core.CanimationPreset

internal val exampleCategoriesChunk04: List<ExampleCategory> = listOf(
        ExampleCategory(
            id = "elastic",
            title = "Elastic",
            subtitle = "Elastic spring-like effects",
            accentLabel = "ENTRANCE",
            tags = listOf("ENTRANCE"),
            examples = listOf(
                ExampleItem("Elastic In", "Elastic stretch entry", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Elastic.In,\n)", effect = Canimation.Elastic.In),
                ExampleItem("Elastic Stretch", "Full elastic stretch", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Elastic.Stretch,\n)", effect = Canimation.Elastic.Stretch),
                ExampleItem("Elastic Squash", "Squash compression", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Elastic.Squash,\n)", effect = Canimation.Elastic.Squash),
                ExampleItem("Elastic Snap", "Snappy elastic entry", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Elastic.Snap,\n)", effect = Canimation.Elastic.Snap),
                ExampleItem("Elastic Wobble", "Wobbly elastic", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Elastic.Wobble,\n)", effect = Canimation.Elastic.Wobble),
            ),
        ),
        ExampleCategory(
            id = "cinematic",
            title = "Cinematic",
            subtitle = "Cinematic film-inspired effects",
            accentLabel = "ENTRANCE",
            tags = listOf("ENTRANCE"),
            examples = listOf(
                ExampleItem("Cinematic Curtain", "Curtain reveal from top", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Cinematic.Curtain,\n)", effect = Canimation.Cinematic.Curtain),
                ExampleItem("Cinematic Zoom Pan", "Camera zoom pan", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Cinematic.ZoomPan,\n)", effect = Canimation.Cinematic.ZoomPan),
                ExampleItem("Cinematic Dolly", "Dolly zoom effect", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Cinematic.Dolly,\n)", effect = Canimation.Cinematic.Dolly),
                ExampleItem("Cinematic Reveal", "Subtle cinematic reveal", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Cinematic.Reveal,\n)", effect = Canimation.Cinematic.Reveal),
                ExampleItem("Cinematic Fade", "Fade to black style", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Cinematic.FadeToBlack,\n)", effect = Canimation.Cinematic.FadeToBlack),
                ExampleItem("Cinematic Dramatic", "Dramatic entrance", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Cinematic.Dramatic,\n)", effect = Canimation.Cinematic.Dramatic),
            ),
        ),
        ExampleCategory(
            id = "playful",
            title = "Playful",
            subtitle = "Playful fun effects",
            accentLabel = "ENTRANCE",
            tags = listOf("ENTRANCE"),
            examples = listOf(
                ExampleItem("Playful Wiggle", "Fun wiggle entry", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Playful.Wiggle,\n)", effect = Canimation.Playful.Wiggle),
                ExampleItem("Playful Hop", "Hop bounce entry", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Playful.Hop,\n)", effect = Canimation.Playful.Hop),
                ExampleItem("Playful Spin", "Playful spin entry", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Playful.Spin,\n)", effect = Canimation.Playful.Spin),
                ExampleItem("Playful Pop", "Quick playful pop", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Playful.Pop,\n)", effect = Canimation.Playful.Pop),
                ExampleItem("Playful Twirl", "Twirling entry", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Playful.Twirl,\n)", effect = Canimation.Playful.Twirl),
                ExampleItem("Playful Boing", "Spring boing effect", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Playful.Boing,\n)", effect = Canimation.Playful.Boing),
            ),
        ),
        ExampleCategory(
            id = "diagonal",
            title = "Diagonal",
            subtitle = "Diagonal movement entries",
            accentLabel = "MOVEMENT",
            tags = listOf("ENTRANCE", "MOVEMENT"),
            examples = listOf(
                ExampleItem("Diagonal Top Left", "Enter from top-left corner", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Diagonal.TopLeft,\n)", effect = Canimation.Diagonal.TopLeft),
                ExampleItem("Diagonal Top Right", "Enter from top-right corner", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Diagonal.TopRight,\n)", effect = Canimation.Diagonal.TopRight),
                ExampleItem("Diagonal Bottom Left", "Enter from bottom-left corner", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Diagonal.BottomLeft,\n)", effect = Canimation.Diagonal.BottomLeft),
                ExampleItem("Diagonal Bottom Right", "Enter from bottom-right corner", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Diagonal.BottomRight,\n)", effect = Canimation.Diagonal.BottomRight),
                ExampleItem("Diagonal Subtle", "Subtle diagonal entry", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Diagonal.Subtle,\n)", effect = Canimation.Diagonal.Subtle),
            ),
        ),
        ExampleCategory(
            id = "shrink",
            title = "Shrink",
            subtitle = "Shrink-from-large entry animations",
            accentLabel = "SCALE",
            tags = listOf("ENTRANCE", "SCALE"),
            examples = listOf(
                ExampleItem("Shrink Out", "Shrink from oversized", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Shrink.Out,\n)", effect = Canimation.Shrink.Out),
                ExampleItem("Shrink Subtle", "Subtle shrink entry", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Shrink.Subtle,\n)", effect = Canimation.Shrink.Subtle),
                ExampleItem("Shrink Rotate", "Shrink with rotation", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Shrink.Rotate,\n)", effect = Canimation.Shrink.Rotate),
                ExampleItem("Shrink Fade Down", "Shrink and drift down", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Shrink.FadeDown,\n)", effect = Canimation.Shrink.FadeDown),
            ),
        ),
        ExampleCategory(
            id = "tilt",
            title = "Tilt",
            subtitle = "Tilting skew entries",
            accentLabel = "ROTATE",
            tags = listOf("ENTRANCE", "ROTATE"),
            examples = listOf(
                ExampleItem("Tilt Left", "Tilt in from left", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Tilt.Left,\n)", effect = Canimation.Tilt.Left),
                ExampleItem("Tilt Right", "Tilt in from right", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Tilt.Right,\n)", effect = Canimation.Tilt.Right),
                ExampleItem("Tilt Up", "Tilt entry from above", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Tilt.Up,\n)", effect = Canimation.Tilt.Up),
                ExampleItem("Tilt Down", "Tilt entry from below", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Tilt.Down,\n)", effect = Canimation.Tilt.Down),
                ExampleItem("Tilt Swing", "Swinging tilt entry", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Tilt.Swing,\n)", effect = Canimation.Tilt.Swing),
            ),
        ),
        ExampleCategory(
            id = "float",
            title = "Float",
            subtitle = "Gentle floating animations",
            accentLabel = "SUBTLE",
            tags = listOf("ENTRANCE", "SUBTLE"),
            examples = listOf(
                ExampleItem("Float Up", "Float up gently", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Float.Up,\n)", effect = Canimation.Float.Up),
                ExampleItem("Float Down", "Float down gently", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Float.Down,\n)", effect = Canimation.Float.Down),
                ExampleItem("Float Gentle", "Very gentle float", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Float.Gentle,\n)", effect = Canimation.Float.Gentle),
                ExampleItem("Float Scale Up", "Float with subtle scale", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Float.ScaleUp,\n)", effect = Canimation.Float.ScaleUp),
            ),
        ),
        ExampleCategory(
            id = "drop",
            title = "Drop",
            subtitle = "Gravity-like drop entries",
            accentLabel = "MOVEMENT",
            tags = listOf("ENTRANCE", "MOVEMENT"),
            examples = listOf(
                ExampleItem("Drop In", "Standard drop entry", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Drop.In,\n)", effect = Canimation.Drop.In),
                ExampleItem("Drop Heavy", "Heavy slam drop", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Drop.Heavy,\n)", effect = Canimation.Drop.Heavy),
                ExampleItem("Drop Light", "Light feather drop", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Drop.Light,\n)", effect = Canimation.Drop.Light),
                ExampleItem("Drop Rotate", "Drop with rotation", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Drop.Rotate,\n)", effect = Canimation.Drop.Rotate),
            ),
        ),
        ExampleCategory(
            id = "rise",
            title = "Rise",
            subtitle = "Ascending rise entries",
            accentLabel = "MOVEMENT",
            tags = listOf("ENTRANCE", "MOVEMENT"),
            examples = listOf(
                ExampleItem("Rise In", "Standard rise entry", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Rise.In,\n)", effect = Canimation.Rise.In),
                ExampleItem("Rise Slow", "Slow rising entry", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Rise.Slow,\n)", effect = Canimation.Rise.Slow),
                ExampleItem("Rise Scale", "Rise with scale", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Rise.Scale,\n)", effect = Canimation.Rise.Scale),
                ExampleItem("Rise Rotate", "Rise with rotation", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Rise.Rotate,\n)", effect = Canimation.Rise.Rotate),
            ),
        ),
        ExampleCategory(
            id = "stretch",
            title = "Stretch",
            subtitle = "Stretch deformation entries",
            accentLabel = "SCALE",
            tags = listOf("ENTRANCE", "SCALE"),
            examples = listOf(
                ExampleItem("Stretch Horizontal", "Horizontal stretch entry", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Stretch.Horizontal,\n)", effect = Canimation.Stretch.Horizontal),
                ExampleItem("Stretch Vertical", "Vertical stretch entry", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Stretch.Vertical,\n)", effect = Canimation.Stretch.Vertical),
                ExampleItem("Stretch Both", "Stretch from both axes", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Stretch.Both,\n)", effect = Canimation.Stretch.Both),
                ExampleItem("Stretch Snap", "Stretch with snap", "Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Stretch.Snap,\n)", effect = Canimation.Stretch.Snap),
            ),
        ),
        ExampleCategory(
            id = "navigation-ui",
            title = "Navigation UI",
            subtitle = "Animated navigation components",
            accentLabel = "UI",
            tags = listOf("UI", "NAVIGATION"),
            examples = listOf(
                ExampleItem("Animated Breadcrumb", "Staggered breadcrumb trail", "AnimatedBreadcrumb(modifier = Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Fade.Up,\n))", demoType = DemoType.Component, componentKey = ComponentDemoKeys.AnimatedBreadcrumb),
                ExampleItem("Animated Nav Item", "Bottom nav with animated selection", "AnimatedNavItem(modifier = Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Drop.Light,\n))", demoType = DemoType.Component, componentKey = ComponentDemoKeys.AnimatedNavItem),
            ),
        ),
        ExampleCategory(
            id = "data-display",
            title = "Data Display",
            subtitle = "Animated data visualization components",
            accentLabel = "UI",
            tags = listOf("UI", "DATA"),
            examples = listOf(
                ExampleItem("Animated Timeline", "Staggered event timeline", "AnimatedTimeline(modifier = Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Rise.In,\n))", demoType = DemoType.Component, componentKey = ComponentDemoKeys.AnimatedTimeline),
                ExampleItem("Animated Stat Card", "Stats card with tilt entry", "AnimatedStatCard(modifier = Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Tilt.Swing,\n))", demoType = DemoType.Component, componentKey = ComponentDemoKeys.AnimatedStatCard),
                ExampleItem("Animated KPI", "Key performance indicators", "AnimatedKpi(modifier = Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Rise.Scale,\n))", demoType = DemoType.Component, componentKey = ComponentDemoKeys.AnimatedKpi),
                ExampleItem("Animated Rating", "Star rating animation", "AnimatedRating(modifier = Modifier.canimation(\n    visible = isVisible,\n    effect = Canimation.Scale.Pop,\n))", demoType = DemoType.Component, componentKey = ComponentDemoKeys.AnimatedRating),
            ),
        ),
)
