name: Workflow Name

on:
  pull_request:
  push:
    branches: [main, dev]

permissions:
  contents: read

concurrency:
  group: workflow-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up build environment
        uses: ./.github/actions/setup-build
      - name: Run checks
        run: ./gradlew allTests --max-workers=2
