name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-build
      - run: ./gradlew allTests koverVerify --max-workers=2

  publish:
    needs: check
    runs-on: ubuntu-24.04
    environment: release
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-build
      - name: Publish
        env:
          CANIMATION_MAVEN_URL: ${{ secrets.CANIMATION_MAVEN_URL }}
          CANIMATION_MAVEN_USERNAME: ${{ secrets.CANIMATION_MAVEN_USERNAME }}
          CANIMATION_MAVEN_PASSWORD: ${{ secrets.CANIMATION_MAVEN_PASSWORD }}
          CANIMATION_SIGNING_KEY: ${{ secrets.CANIMATION_SIGNING_KEY }}
          CANIMATION_SIGNING_PASSWORD: ${{ secrets.CANIMATION_SIGNING_PASSWORD }}
          CANIMATION_SIGNING_KEY_ID: ${{ secrets.CANIMATION_SIGNING_KEY_ID }}
        run: ./gradlew publish
